// <auto-generated />
using AuBoulot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AuBoulot.Web.Migrations
{
    [DbContext(typeof(AuBoulotContext))]
    [Migration("20171225144707_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuBoulot.Web.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Direction");

                    b.Property<int>("Evalution");

                    b.Property<Guid?>("JobOpportunityId");

                    b.Property<Guid?>("NextActivityId");

                    b.Property<string>("Notes");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("JobOpportunityId")
                        .IsUnique()
                        .HasFilter("[JobOpportunityId] IS NOT NULL");

                    b.HasIndex("NextActivityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("AuBoulot.Web.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AuBoulot.Web.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("FullName");

                    b.Property<string>("SimpleName");

                    b.Property<string>("WebSite");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("AuBoulot.Web.Models.JobOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("MaxSalary");

                    b.Property<int>("MinSalary");

                    b.Property<Guid?>("ParentCompanyId");

                    b.Property<string>("Source");

                    b.Property<string>("Title");

                    b.Property<Guid?>("WorkAddressId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId");

                    b.HasIndex("WorkAddressId");

                    b.ToTable("JobOpportunity");
                });

            modelBuilder.Entity("AuBoulot.Web.Models.Activity", b =>
                {
                    b.HasOne("AuBoulot.Web.Models.JobOpportunity", "JobOpportunity")
                        .WithOne("FirstActivity")
                        .HasForeignKey("AuBoulot.Web.Models.Activity", "JobOpportunityId");

                    b.HasOne("AuBoulot.Web.Models.Activity", "NextActivity")
                        .WithMany()
                        .HasForeignKey("NextActivityId");
                });

            modelBuilder.Entity("AuBoulot.Web.Models.JobOpportunity", b =>
                {
                    b.HasOne("AuBoulot.Web.Models.Company", "ParentCompany")
                        .WithMany()
                        .HasForeignKey("ParentCompanyId");

                    b.HasOne("AuBoulot.Web.Models.Address", "WorkAddress")
                        .WithMany()
                        .HasForeignKey("WorkAddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
